-- SmartPages Cloud: run this once in Supabase SQL Editor.
-- The bucket stays private; users can only access their own folder.

create extension if not exists pgcrypto;

create table if not exists public.cloud_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'SmartPages document',
  format text not null default 'markdown' check (format in ('markdown', 'html', 'text')),
  content text not null default '',
  document_type text not null default 'generated' check (document_type = 'generated'),
  revision integer not null default 1 check (revision > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cloud_documents
  add column if not exists document_type text not null default 'generated';

create table if not exists public.cloud_document_versions (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.cloud_documents(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'SmartPages document',
  format text not null default 'markdown' check (format in ('markdown', 'html', 'text')),
  content text not null default '',
  revision integer not null check (revision > 0),
  event text not null default 'cloud_save' check (event in ('generated', 'cloud_save')),
  created_at timestamptz not null default now(),
  unique (document_id, revision)
);

create index if not exists cloud_document_versions_user_created_idx
  on public.cloud_document_versions (user_id, created_at desc);

insert into public.cloud_document_versions (document_id, user_id, title, format, content, revision, event, created_at)
select id, user_id, title, format, content, revision, 'cloud_save', updated_at
from public.cloud_documents
on conflict (document_id, revision) do nothing;

create index if not exists cloud_documents_user_updated_idx
  on public.cloud_documents (user_id, updated_at desc);

alter table public.cloud_documents enable row level security;
alter table public.cloud_document_versions enable row level security;

drop policy if exists "Users can read their cloud documents" on public.cloud_documents;
create policy "Users can read their cloud documents"
  on public.cloud_documents for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create their cloud documents" on public.cloud_documents;
create policy "Users can create their cloud documents"
  on public.cloud_documents for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can update their cloud documents" on public.cloud_documents;
create policy "Users can update their cloud documents"
  on public.cloud_documents for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete their cloud documents" on public.cloud_documents;
create policy "Users can delete their cloud documents"
  on public.cloud_documents for delete
  using (auth.uid() = user_id);

drop policy if exists "Users can read their cloud document versions" on public.cloud_document_versions;
create policy "Users can read their cloud document versions"
  on public.cloud_document_versions for select
  using (auth.uid() = user_id);

drop policy if exists "Users can create their cloud document versions" on public.cloud_document_versions;
create policy "Users can create their cloud document versions"
  on public.cloud_document_versions for insert
  with check (auth.uid() = user_id);

create or replace function public.save_generated_document(
  p_id uuid,
  p_title text,
  p_format text,
  p_content text,
  p_expected_revision integer default null,
  p_event text default 'cloud_save'
)
returns public.cloud_documents
language plpgsql
security invoker
set search_path = public
as $$
declare
  saved public.cloud_documents;
begin
  if auth.uid() is null then
    raise exception 'AUTH_REQUIRED' using errcode = '42501';
  end if;
  if p_format not in ('markdown', 'html', 'text') or p_event not in ('generated', 'cloud_save') then
    raise exception 'INVALID_DOCUMENT' using errcode = '22023';
  end if;

  if p_expected_revision is null then
    insert into public.cloud_documents (id, user_id, title, format, content, document_type)
    values (p_id, auth.uid(), left(coalesce(p_title, 'SmartPages document'), 200), p_format, coalesce(p_content, ''), 'generated')
    returning * into saved;
  else
    update public.cloud_documents
    set title = left(coalesce(p_title, 'SmartPages document'), 200),
        format = p_format,
        content = coalesce(p_content, ''),
        revision = revision + 1,
        updated_at = now()
    where id = p_id
      and user_id = auth.uid()
      and document_type = 'generated'
      and revision = p_expected_revision
    returning * into saved;
    if not found then
      raise exception 'VERSION_CONFLICT' using errcode = '40001';
    end if;
  end if;

  insert into public.cloud_document_versions
    (document_id, user_id, title, format, content, revision, event, created_at)
  values
    (saved.id, saved.user_id, saved.title, saved.format, saved.content, saved.revision, p_event, saved.updated_at);
  return saved;
end;
$$;

revoke all on function public.save_generated_document(uuid, text, text, text, integer, text) from public;
grant execute on function public.save_generated_document(uuid, text, text, text, integer, text) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'smartpages-assets',
  'smartpages-assets',
  false,
  10485760,
  array['image/png', 'image/jpeg', 'image/gif', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Users can read their SmartPages assets" on storage.objects;
create policy "Users can read their SmartPages assets"
  on storage.objects for select
  using (
    bucket_id = 'smartpages-assets'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can upload their SmartPages assets" on storage.objects;
create policy "Users can upload their SmartPages assets"
  on storage.objects for insert
  with check (
    bucket_id = 'smartpages-assets'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can update their SmartPages assets" on storage.objects;
create policy "Users can update their SmartPages assets"
  on storage.objects for update
  using (
    bucket_id = 'smartpages-assets'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "Users can delete their SmartPages assets" on storage.objects;
create policy "Users can delete their SmartPages assets"
  on storage.objects for delete
  using (
    bucket_id = 'smartpages-assets'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
